/** One emoji per family, matched to the catalog blurb / vibe — not a scraped post. */
const MARKS: Record<string, string> = {
  "aura-farming": "😎",
  rickroll: "🕺",
  skibidi: "🚽",
  "sixty-seven": "🧸",
  crashout: "😡",
  "we-are-so-back": "📈",
  npc: "🧍",
  "italian-brainrot": "🦈",
  mogging: "👑",
  delulu: "✨",
  "locked-in": "🔒",
  ragebait: "🎣",
  glazing: "🍯",
  yapping: "🗣️",
  gooning: "🫠",
  rizz: "😏",
  "touch-grass": "🌱",
  cooked: "💀",
  "its-so-over": "📉",
  "let-him-cook": "👨‍🍳",
  sigma: "🐺",
  brainrot: "🧠",
  "ai-slop": "🥫",
  "main-character": "🎬",
  situationship: "🪢",
  backrooms: "🚪",
  "skill-issue": "🎮",
  "down-bad": "🥺",
  ohio: "🌽",
  "its-giving": "💅",
  "the-voices": "👻",
  "chronically-online": "💻",
  "talking-stage": "💬",
  "nepo-baby": "👶",
  "roman-empire": "🏛️",
  "the-ick": "🤢",
  clanker: "🤖",
  allegations: "📋",
  "understood-the-assignment": "💯",
  looksmaxxing: "🪞",
  "pick-me": "🙋",
  tweaking: "😵",
  "no-cap": "🧢",
  gigachad: "🗿",
};

export function memeEmoji(slug: string, fallbackName = "?"): string {
  return MARKS[slug] ?? fallbackName.slice(0, 1);
}
